### ISSUE TITLE
JDK17 does not work.

### ISSUE THREAD

**Issue by nivanov** [nivanov/cosplay#49]
❯ java -cp modules/cosplay/target/cosplay-0.1.1-all-deps.jar org.cosplay.games.pong.CPPongGame
Exception in thread "main" java.lang.IllegalAccessError: class org.cosplay.CPEngine$ (in unnamed module @0x71ea80a6) cannot access class com.sun.javafx.application.PlatformImpl (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.application to unnamed module @0x71ea80a6
        at org.cosplay.CPEngine$.init(CPEngine.scala:268)
        at org.cosplay.games.pong.CPPongGame$.main(CPPongGame.scala:76)
        at org.cosplay.games.pong.CPPongGame.main(CPPongGame.scala)

**Comment by nivanov** [comment]
Updated docs.
