### ISSUE TITLE
ArrayIndexOutOfBoundsException in CPSlideInShader

### ISSUE THREAD

**Issue by nivanov** [nivanov/cosplay#67]
java.lang.ArrayIndexOutOfBoundsException: Index 48 out of bounds for length 46
        at org.cosplay.prefabs.shaders.CPSlideInShader.render$$anonfun$1(CPSlideInShader.scala:127)
        at org.cosplay.CPRect.loop(CPRect.scala:214)
        at org.cosplay.prefabs.shaders.CPSlideInShader.render(CPSlideInShader.scala:140)
        at org.cosplay.CPEngine$.gameLoop$$anonfun$10$$anonfun$2(CPEngine.scala:1045)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:896)
        at org.cosplay.CPEngine$.gameLoop$$anonfun$10(CPEngine.scala:1045)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:896)
        at org.cosplay.CPEngine$.gameLoop(CPEngine.scala:1045)
        at org.cosplay.CPEngine$.startGame(CPEngine.scala:463)
        at org.cosplay.CPEngine$.startGame(CPEngine.scala:480)
        at org.cosplay.games.pong.CPPongGame$.main(CPPongGame.scala:77)
        at org.cosplay.games.pong.CPPongGame.main(CPPongGame.scala)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by nivanov** [comment]
Replicate by resizing the native terminal window in any game...
